name: Run Anime Crawler

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # 每天台北時間凌晨1點（UTC+8），即UTC 17:00

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run anime_crawler.py
        run: python anime_crawler.py

      - name: Upload anime_data.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: anime_data
          path: anime_data.json