name: Run Anime Crawler

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # 每天台北時間凌晨1點（UTC+8），即UTC 17:00

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run anime_crawler.py
        run: python anime_crawler.py

      - name: Commit and push anime_data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add anime_data.json
          git commit -m "Update anime_data.json [auto]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload anime_data.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: anime_data
          path: anime_data.json